MOV REG_US $1
MOV REG_DS $1
MOV REG_UM $0
MOV REG_DM $5
MOV REG_UH $1
MOV REG_DH $2
MOV REG_AM_UH $9
MOV REG_AM_DH $0
STORE REG_US LCD_US
STORE REG_DS LCD_DS
STORE REG_UM LCD_UM
STORE REG_DM LCD_DM
STORE REG_UH LCD_UH
STORE REG_DH LCD_DH
LINHA_Y:
LOAD REG_TEMPO IO_TEMPO
CMP REG_TEMPO $1
JNE LINHA_Y
LOAD REG_CLEAR CLEAR_TEMPO
ADD REG_US $1
CMP REG_US $10
JNE LINHA_Z2
MOV REG_US $0
ADD REG_DS $1
CMP REG_DS $6
JNE LINHA_Z2
MOV REG_DS $0
ADD REG_UM $1
CMP REG_UM $10
JNE LINHA_Z2
MOV REG_UM $0
ADD REG_DM $1
CMP REG_DM $6
JNE LINHA_Z2
MOV REG_DM $0
ADD REG_UH $1
ADD REG_AM_UH $1
CMP REG_UH $10
JNE LINHA_Z1
MOV REG_UH $0
ADD REG_DH $1
LINHA_Z1:
CMP REG_AM_UH $10
JNE LINHA_Z2
MOV REG_AM_UH $0
ADD REG_AM_DH $1
LINHA_Z2:
CMP REG_DH $2
JNE LINHA_X1
CMP REG_UH $4
JNE LINHA_X1
MOV REG_US $0
MOV REG_DS $0
MOV REG_UM $0
MOV REG_DM $0
MOV REG_UH $0
MOV REG_DH $0
LINHA_X1:
CMP REG_AM_DH $1
JNE LINHA_X2
CMP REG_AM_UH $2
JNE LINHA_X2
MOV REG_US $0
MOV REG_DS $0
MOV REG_UM $0
MOV REG_DM $0
MOV REG_AM_UH $0
MOV REG_AM_DH $0
LINHA_X2:
STORE REG_US LCD_US
STORE REG_DS LCD_DS
STORE REG_UM LCD_UM
STORE REG_DM LCD_DM
LOAD REG_SWITCH IO_SWITCH
MOV REG_SWITCH $1
CMP REG_SWITCH $1
JNE LINHA_B12
STORE REG_UH LCD_UH
STORE REG_DH LCD_DH
JUMP LINHA_Y
LINHA_B12:
STORE REG_AM_UH LCD_UH
STORE REG_AM_DH LCD_DH
JUMP LINHA_Y