MOV REG_US $1
MOV REG_DS $3
MOV REG_UM $4
MOV REG_DM $5
MOV REG_UH $6
MOV REG_DH $7
STORE REG_DS LCD_DS
STORE REG_UM LCD_UM
STORE REG_DM LCD_DM
STORE REG_UH LCD_UH
STORE REG_DH LCD_DH
STORE REG_US LCD_US
LINHA_A:
LOAD REG_TEMPO IO_TEMPO
STORE REG_TEMPO LCD_UH
ADD REG_US $1
STORE REG_US LCD_US
CMP REG_US $0
JNE LINHA_A
MOV REG_DH $9
STORE REG_DH LCD_DH